### ISSUE TITLE
Allow recycling of large/small steel pulleys

### ISSUE THREAD

**Issue by bpskotch** [twohoursonelife/OneLifeData7#111]
Large/small pulley + scrap bowl = Crucible with scrap steel

Edit: If you do not want me to post suggestions here please let me know. Thanks

**Comment by connorhsm** [comment]
Hey @bpskotch, that kind of content relates to https://github.com/twohoursonelife/OneLifeData7/

Please use the suggestions channel in discord for making a suggestion, I would recommend discussing in a channel like general beforehand.
